#!/bin/bash
PATH="/usr/local/bin:$PATH"
chmod +x "/Users/c4k3ss/Downloads/HISE-develop/tools/Projucer/Projucer.app/Contents/MacOS/Projucer"
cd "`dirname "$0"`"
"/Users/c4k3ss/Downloads/HISE-develop/tools/Projucer/Projucer.app/Contents/MacOS/Projucer" --resave AutogeneratedProject.jucer

set -o pipefail
echo Compiling  TooMuchReverb ...
xcodebuild -project "Builds/MacOSX/TooMuchReverb.xcodeproj" -configuration "Release" -jobs "8" | "/Users/c4k3ss/Downloads/HISE-develop/tools/Projucer/xcbeautify"
